inherit_gem:
  project-tools-ruby-lint: config/rubocop.yml

inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  Include:
    - '.tools/metadata/bin/project-tools-metadata'
    - '.tools/lint/bin/puppet-lint-junit'
    - '.tools/validate/bin/validate-junit'
    - '.tools/module-dependencies/bin/project-tools-module-dependencies'
    - '.tools/**/*.rb'
    - '.tools/**/*.rake'
    - '.tools/**/*.gemspec'
  Exclude:
    - 'concat/**/*'
    - 'debconf/**/*'
    - 'reboot/**/*'
    - 'stdlib/**/*'
    - 'vendor/bundle/**/*'
    # ERB source must be rendered before it becomes valid Ruby.
    - '**/templates/**/*'
