# Managed by puppet
<%- if @interface_correct.nil? -%>
# Monitoring thresholds for check_vnstat_interfaces.
# Format:
# p95_warning <Mbit/s>
# p95_critical <Mbit/s>
# interface <name> p95_warning <Mbit/s>
# interface <name> p95_critical <Mbit/s>
<%- unless @p95_warning.nil? -%>
p95_warning <%= @p95_warning %>
<%- end -%>
<%- unless @p95_critical.nil? -%>
p95_critical <%= @p95_critical %>
<%- end -%>
<%- else -%>
# Interface-specific vnStat monitoring thresholds for <%= @interface_correct %>.
<%- unless @p95_warning.nil? -%>
interface <%= @interface_correct %> p95_warning <%= @p95_warning_correct %>
<%- end -%>
<%- unless @p95_critical.nil? -%>
interface <%= @interface_correct %> p95_critical <%= @p95_critical_correct %>
<%- end -%>
<%- end -%>
