# Managed by puppet
add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Content-Security-Policy "default-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'self'; form-action 'self'" always;
add_header Referrer-Policy "same-origin" always;
<% @webserver_directives.each do |directive| -%>
<%= directive %>
<% end -%>