name: Set up project tooling
description: Install the Ruby tooling bundle using the repository lockfile
runs:
  using: composite
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler: none
    - name: Install the latest stable Bundler
      shell: bash
      run: |
        source "$GITHUB_ACTION_PATH/log.sh"
        ci_begin 'Install Bundler' details
        if gem install bundler; then
            ci_end 0 PASSED complete
        else
            ci_end "$?" ERROR incomplete
        fi
    - name: Install the locked development bundle
      shell: bash
      run: |
        source "$GITHUB_ACTION_PATH/log.sh"
        ci_begin 'Install locked bundle' details
        if bundle install; then
            ci_end 0 PASSED complete
        else
            ci_end "$?" ERROR incomplete
        fi
