# A sample configuration for dhcpcd.
# See dhcpcd.conf(5) for details.

# Set hostname
hostname <%= @communication_hostname %>

# Do NOT request a hostname from DHCP (we provide our own)
nooption host_name

# Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
# Some non-RFC compliant DHCP servers do not reply with this set.
# In this case, comment out duid and enable clientid above.
duid

# Persist interface configuration when dhcpcd exits.
persistent

# vendorclassid is set to blank to avoid sending the default of
# dhcpcd-<version>:<os>:<machine>:<platform>
vendorclassid

# A list of options to request from the DHCP server.
option domain_name_servers, domain_name, domain_search
option classless_static_routes

# Respect the network MTU. This is applied to DHCP routes.
option interface_mtu

# Prevent fallback to link-local IPv4 (169.254.x.x)
noipv4ll

# Rapid commit support.
# Safe to enable by default because it requires the equivalent option set
# on the server to actually work.
option rapid_commit

# A ServerID is required by RFC2131.
require dhcp_server_identifier

<% if @ip_dhcp_v6 -%>
# Generate Stable Private IPv6 Addresses based from the DUID
slaac private
<% else -%>
# If you do not use IPv6, disable it to avoid router solicitations/log spam
noipv6
<% end -%>