# Managed by puppet
network:
  version: 2
<% if !@renderer.nil? -%>
  renderer: <%= @renderer %>
<% end -%>
  ethernets:
    <%= @interface_correct %>:
<% if !@addresses.nil? -%>
<% if @ip_version_v4 -%>
      dhcp4: no
<% end -%>
<% if @ip_version_v6 -%>
      dhcp6: no
<% end -%>
      addresses:
<% @addresses.each do |address| -%>
        - <%= address %>
<% end -%>
<% else -%>
<% if @ip_version_v4 -%>
      dhcp4: <%= @dhcpc_string %>
<% end -%>
<% if @ip_version_v6 -%>
      dhcp6: <%= @dhcpc_string %>
      accept-ra: <%= @ip_ra_string %>
<% end -%>
<% end -%>
<% if !@nameservers.nil? and !@nameservers['addresses'].empty? and !@nameservers['addresses'].nil? and !@nameservers['addresses'].empty? -%>
      nameservers:
        addresses:
<% @nameservers['addresses'].each do |address| -%>
          - <%= address %>
<% end -%>
<% end -%>
      optional: <%= @optional.to_s %>
<% if !@routes.nil? -%>
      routes:
<% @routes.each do |route, object| -%>
<% if !object.nil? and !object.empty? and !object['via'].nil? and !object['via'].empty? -%>
        - to: <%= route %>
<% object.each do |key, value| -%>
          <%= key %>: <%= value.is_a?(TrueClass) || value.is_a?(FalseClass) ? value.to_s : value %>
<% end -%>
<% end -%>
<% end -%>
<% end -%>